config/routes.rb
ShoppingApp::Application.routes.draw do

root 'shops#index'

resources :shops
end

#  Prefix Verb   URI Pattern               Controller#Action
#      root GET    /                         shops#index
#     shops GET    /shops(.:format)          shops#index
#           POST   /shops(.:format)          shops#create
#  new_shop GET    /shops/new(.:format)      shops#new
# edit_shop GET    /shops/:id/edit(.:format) shops#edit
#      shop GET    /shops/:id(.:format)      shops#show
#           PATCH  /shops/:id(.:format)      shops#update
#           PUT    /shops/:id(.:format)      shops#update
#           DELETE /shops/:id(.:format)      shops#destroy

app/models/shop.rb
class Shop < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController

	def index
		@shops = Shop.all
	end

	def show
		@shop = Shop.find(params[:id]) 
	end

	def new
		@shop = Shop.new
	end

	def create
		@shop = Shop.create shop_params
		redirect_to shop_path(@shop)
	end

	def edit
		@shop = Shop.find(params[:id])
	end

	def update
		@shop = Shop.find(params[:id])
		@shop.update shop_params
		redirect_to shop_path(@shop)
	end

	def destroy
		Shop.find(params[:id]).destroy
		redirect_to root_path
	end

	private
    	def shop_params
      		params.require(:shop).permit(:title, :description, :quantity)
    	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ShoppingApp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/shops/edit.html.erb
<div class="edit">
<h2>Edit an item on your shopping list:</h2>
<br />
<%= form_for @shop do |f| %>

  <%= label_tag(:title, "Item:") %>
  <%= f.text_field :title%></br>

  <%= label_tag(:description, "Description:") %> 
  <%= f.text_area :description %></br>

  <%= label_tag(:quantity, "Quantity:") %> 
  <%= f.text_area :quantity %></br>

  <%= f.submit "Update", :class => "btn btn-info" %>
<% end %>

<br />

<%= link_to "Back To Shopping List", shops_path, :class => "btn btn-success" %>
</div>

app/views/shops/index.html.erb
<h2 style=text-align:center;>Welcome to the interactive shopping list!</h2>
	<div class="indexbutton">
		<%= link_to "Add a new item", new_shop_path, :class => "btn btn-success" %>
	</div>

	<div class="index">
		<h3>Items currently on your shopping list:</h3>
<% @shops.each do |shop| %>
    <li>
    	<%= link_to shop.title, shop_path(shop.id), :class => "btn btn-primary"%>
    	<%= link_to "edit", edit_shop_path(shop[:id]), :class => "btn btn-info" %>
    	<%= link_to "delete", shop, method: :delete, data: { confirm: "You sure?" }, :class => "btn btn-danger" %>
    </li>
<% end %>
</div>

app/views/shops/new.html.erb
<div class="new">

<h2>Add a new item to your list:</h2>
<%= form_for @shop do |f| %>

  <%= label_tag(:title, "Items:") %>
  <%= f.text_field :title %></br>

  <%= label_tag(:description, "Description:") %> 
  <%= f.text_area :description %></br>

  <%= label_tag(:quantity, "Quantity:") %> 
  <%= f.text_area :quantity %></br>

  <%= f.submit "Create", :class => "btn btn-info" %>
<% end %>

<br />

<%= link_to "Back To Shopping List", shops_path, :class => "btn btn-success"%>

</div>

app/views/shops/show.html.erb
<div class="show">

<h2>Items to buy:</h2>
	<p><strong>Items:</strong> <%= @shop.title%></p>
	<p><strong>Description:</strong> <%= @shop.description%></p>
	<p><strong>Quantity:</strong> <%= @shop.quantity%></p>

<%= link_to "Back To Shopping List", shops_path, :class => "btn btn-success"%>

</div>